---
title: "Data Manipulation"
output: github_document
---


```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import some data

I want to import `FAS_litters.csv`


```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


## select

```{r}
select(litters_df, group, litter_number, gd0_weight, pups_born_alive)

select(litters_df, group:gd_of_birth)

select(litters_df, -pups_survive)

select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

## filter

Get rid of rows

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)

filter(litters_df, pups_survive != 4)

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, group == "Con7", gd_of_birth == 20)

drop_na(litters_df, gd0_weight)

drop_na(litters_df)
```


## mutate

Add or change columns

```{r}
mutate(
  litters_df, 
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## arrange

rearrange data

```{r}
arrange(litters_df, gd_of_birth, gd0_weight)
```

